server:
  port: 8008
spring:
  profiles:
    active: dev
  datasource:
    url: 'jdbc:h2:mem:fhir'
    driverClassName: org.h2.Driver
    username: root
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: mysql
    hibernate:
      ddl-auto: update
      show-sql: true